env:
  mocha: true
  browser: true
  es6: true
  jest: true
extends:
  - airbnb
parser: '@babel/eslint-parser'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  requireConfigFile: false
  babelOptions: 
    presets: ['@babel/preset-react']
plugins:
  - react
  - flowtype
rules:
  flowtype/define-flow-type: 2
  import/no-unresolved: off
  react/jsx-filename-extension: off
  react/destructuring-assignment: off
  react/no-unescaped-entities: off
  react/button-has-type: off
  radix: off
  no-underscore-dangle: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/interactive-supports-focus: off
  jsx-a11y/anchor-has-content: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/mouse-events-have-key-events: off
  jsx-a11y/no-noninteractive-element-interactions: off
  no-alert: off
  no-unused-expressions: ['error', { allowShortCircuit: true }]
  global-require: off
  import/no-absolute-path: off
  arrow-parens: [2, 'always', { 'requireForBlockBody': false }]
  import/extensions: off
  no-param-reassign: ['error', { props: true, ignorePropertyModificationsFor: ['draft', 'req', 'e', 'acc'] }]
  implicit-arrow-linebreak: off
  comma-dangle: ['error', 'never']
  react/prop-types: off